Homeworks
1. Create a NumPy array of integers from 1 to 10 (inclusive).
2. Calculate the square of each element in the array.
3. Find the sum, mean, and standard deviation of the squared array.

In [2]:
import numpy as np

In [4]:
#1. Create a NumPy array of integers from 1 to 10 (inclusive).

arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
#2. Calculate the square of each element in the array.

square_arr=arr**2
print(square_arr)

[  1   4   9  16  25  36  49  64  81 100]


In [10]:
#3. Find the sum, mean, and standard deviation of the squared array.

print(f'SUM: {np.sum(square_arr)}')
print(f'Mean: {np.mean(square_arr)}')
print(f'Standard deviation: {np.std(square_arr)}')

SUM: 385
Mean: 38.5
Standard deviation: 32.41990129534635


KAGGLE HOMEWORKS

In [ ]:
#6
z=np.zeros(15)
z[0]=1
z[14]=1
print(z)

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


In [ ]:
#7
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#8
print(a[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [17]:
#9
arr=np.arange(0, 9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
#10. Find indices of non-zero elements from [1,2,0,0,4,0] 

indices=[1,2,0,0,4,0] 
non_zero=np.nonzero(indices)
print(non_zero)

(array([0, 1, 4]),)


In [19]:
#11. Create a 3x3 identity matrix

arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
#12. Create a 3x3x3 array with random values

arr=np.random.random((3,3,3))
print(arr)

[[[0.14375161 0.25648017 0.5049102 ]
  [0.17403191 0.92449186 0.25900911]
  [0.68756727 0.66074514 0.72933423]]

 [[0.85277119 0.08980521 0.53806277]
  [0.31452536 0.76921703 0.3011445 ]
  [0.80624117 0.88205964 0.02599831]]

 [[0.45789762 0.1335645  0.77110969]
  [0.49662976 0.16363485 0.28998639]
  [0.55936    0.96852008 0.84211768]]]


In [25]:
#13. Create a 10x10 array with random values and find the minimum and maximum values

arr=np.random.random((10,10))
print(arr.max())
print(arr.min())

0.997771131531077
0.0037367716728246014


In [28]:
#14. Create a random vector of size 30 and find the mean value

v=np.random.random((30))
m=v.mean()
print(m)

0.542110688577912


In [33]:
#15. Create a 2d array with 1 on the border and 0 inside

arr=np.ones((10,10))
arr[1:-1,1:-1]=0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [34]:
#16. How to add a border (filled with 0's) around an existing array?

arr=np.zeros((10,10))
arr[1:-1,1:-1]=1
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
#19. Create a 8x8 matrix and fill it with a checkerboard pattern

arr=np.zeros((8, 8))
arr[::2, 1::2]=1
arr[1::2, ::2]=1
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])